[package]
name = "datagen"
version = "0.1.0"
authors = ["Yushi OMOTE <yushi.omote@sbibits.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
rmp-serde = "0.14"
derive-new = "0.5"
lazy_static = "1.4"
structopt = "0.3"
indexmap = { version = "1.6", features = ["serde-1"] }
