[package]
name = "datagen"
version = "0.1.0"
authors = ["YushiOMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
derive-new = "0.5"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
