[package]
name = "tool"
version = "0.1.0"
authors = ["YushiOMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
tera = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
tera-text-filters = "1.0"
walkdir = "2.3"
