name: coverage

on: [push]

jobs:
  build:
    name: Check coverage ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9-dev]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Install dependencies
        run: |
          pip install pipenv
          make setup python-version=${{ matrix.python }} build-opt=''
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cdebug-assertions=no -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTDOCFLAGS: "-Cpanic=abort"
      - name: Test
        run: |
          make test
          make coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
