name: release

on: [push]

jobs:
  build-windows:
    name: Release for windows
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          cargo install maturin
          maturin build --release -m perde/Cargo.toml -i python

  build-macos:
    name: Release for macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: |
          cargo install maturin
          maturin build --release -m perde/Cargo.toml -i python3.7 python3.8 python3.9

  build-linux:
    name: Release for manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/io konstin2/maturin build --release -m /io/perde/Cargo.toml -i python3.7 python3.8 python3.9
