name: tests

on: [push]

jobs:
  build:
    name: Test ${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9-dev]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install pipenv
          make setup python-version=${{ matrix.python }}
      - name: Lint
        run: make lint
      - name: Test
        run: make test
